/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AboutSection {
    }
    interface AdminDashboard {
    }
    interface AdminLogin {
    }
    interface BenefitsSection {
    }
    interface ContactSection {
    }
    interface FooterSection {
    }
    interface HeaderSection {
    }
    interface HeroSection {
    }
    interface HomePage {
    }
    interface JoinUsSection {
    }
    interface LoginSection {
    }
    interface MyRouter {
    }
    interface SignInSection {
    }
    interface SportsSection {
    }
    interface SubscriptionSection {
    }
}
declare global {
    interface HTMLAboutSectionElement extends Components.AboutSection, HTMLStencilElement {
    }
    var HTMLAboutSectionElement: {
        prototype: HTMLAboutSectionElement;
        new (): HTMLAboutSectionElement;
    };
    interface HTMLAdminDashboardElement extends Components.AdminDashboard, HTMLStencilElement {
    }
    var HTMLAdminDashboardElement: {
        prototype: HTMLAdminDashboardElement;
        new (): HTMLAdminDashboardElement;
    };
    interface HTMLAdminLoginElement extends Components.AdminLogin, HTMLStencilElement {
    }
    var HTMLAdminLoginElement: {
        prototype: HTMLAdminLoginElement;
        new (): HTMLAdminLoginElement;
    };
    interface HTMLBenefitsSectionElement extends Components.BenefitsSection, HTMLStencilElement {
    }
    var HTMLBenefitsSectionElement: {
        prototype: HTMLBenefitsSectionElement;
        new (): HTMLBenefitsSectionElement;
    };
    interface HTMLContactSectionElement extends Components.ContactSection, HTMLStencilElement {
    }
    var HTMLContactSectionElement: {
        prototype: HTMLContactSectionElement;
        new (): HTMLContactSectionElement;
    };
    interface HTMLFooterSectionElement extends Components.FooterSection, HTMLStencilElement {
    }
    var HTMLFooterSectionElement: {
        prototype: HTMLFooterSectionElement;
        new (): HTMLFooterSectionElement;
    };
    interface HTMLHeaderSectionElement extends Components.HeaderSection, HTMLStencilElement {
    }
    var HTMLHeaderSectionElement: {
        prototype: HTMLHeaderSectionElement;
        new (): HTMLHeaderSectionElement;
    };
    interface HTMLHeroSectionElement extends Components.HeroSection, HTMLStencilElement {
    }
    var HTMLHeroSectionElement: {
        prototype: HTMLHeroSectionElement;
        new (): HTMLHeroSectionElement;
    };
    interface HTMLHomePageElement extends Components.HomePage, HTMLStencilElement {
    }
    var HTMLHomePageElement: {
        prototype: HTMLHomePageElement;
        new (): HTMLHomePageElement;
    };
    interface HTMLJoinUsSectionElement extends Components.JoinUsSection, HTMLStencilElement {
    }
    var HTMLJoinUsSectionElement: {
        prototype: HTMLJoinUsSectionElement;
        new (): HTMLJoinUsSectionElement;
    };
    interface HTMLLoginSectionElement extends Components.LoginSection, HTMLStencilElement {
    }
    var HTMLLoginSectionElement: {
        prototype: HTMLLoginSectionElement;
        new (): HTMLLoginSectionElement;
    };
    interface HTMLMyRouterElement extends Components.MyRouter, HTMLStencilElement {
    }
    var HTMLMyRouterElement: {
        prototype: HTMLMyRouterElement;
        new (): HTMLMyRouterElement;
    };
    interface HTMLSignInSectionElement extends Components.SignInSection, HTMLStencilElement {
    }
    var HTMLSignInSectionElement: {
        prototype: HTMLSignInSectionElement;
        new (): HTMLSignInSectionElement;
    };
    interface HTMLSportsSectionElement extends Components.SportsSection, HTMLStencilElement {
    }
    var HTMLSportsSectionElement: {
        prototype: HTMLSportsSectionElement;
        new (): HTMLSportsSectionElement;
    };
    interface HTMLSubscriptionSectionElement extends Components.SubscriptionSection, HTMLStencilElement {
    }
    var HTMLSubscriptionSectionElement: {
        prototype: HTMLSubscriptionSectionElement;
        new (): HTMLSubscriptionSectionElement;
    };
    interface HTMLElementTagNameMap {
        "about-section": HTMLAboutSectionElement;
        "admin-dashboard": HTMLAdminDashboardElement;
        "admin-login": HTMLAdminLoginElement;
        "benefits-section": HTMLBenefitsSectionElement;
        "contact-section": HTMLContactSectionElement;
        "footer-section": HTMLFooterSectionElement;
        "header-section": HTMLHeaderSectionElement;
        "hero-section": HTMLHeroSectionElement;
        "home-page": HTMLHomePageElement;
        "join-us-section": HTMLJoinUsSectionElement;
        "login-section": HTMLLoginSectionElement;
        "my-router": HTMLMyRouterElement;
        "sign-in-section": HTMLSignInSectionElement;
        "sports-section": HTMLSportsSectionElement;
        "subscription-section": HTMLSubscriptionSectionElement;
    }
}
declare namespace LocalJSX {
    interface AboutSection {
    }
    interface AdminDashboard {
    }
    interface AdminLogin {
    }
    interface BenefitsSection {
    }
    interface ContactSection {
    }
    interface FooterSection {
    }
    interface HeaderSection {
    }
    interface HeroSection {
    }
    interface HomePage {
    }
    interface JoinUsSection {
    }
    interface LoginSection {
    }
    interface MyRouter {
    }
    interface SignInSection {
    }
    interface SportsSection {
    }
    interface SubscriptionSection {
    }
    interface IntrinsicElements {
        "about-section": AboutSection;
        "admin-dashboard": AdminDashboard;
        "admin-login": AdminLogin;
        "benefits-section": BenefitsSection;
        "contact-section": ContactSection;
        "footer-section": FooterSection;
        "header-section": HeaderSection;
        "hero-section": HeroSection;
        "home-page": HomePage;
        "join-us-section": JoinUsSection;
        "login-section": LoginSection;
        "my-router": MyRouter;
        "sign-in-section": SignInSection;
        "sports-section": SportsSection;
        "subscription-section": SubscriptionSection;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "about-section": LocalJSX.AboutSection & JSXBase.HTMLAttributes<HTMLAboutSectionElement>;
            "admin-dashboard": LocalJSX.AdminDashboard & JSXBase.HTMLAttributes<HTMLAdminDashboardElement>;
            "admin-login": LocalJSX.AdminLogin & JSXBase.HTMLAttributes<HTMLAdminLoginElement>;
            "benefits-section": LocalJSX.BenefitsSection & JSXBase.HTMLAttributes<HTMLBenefitsSectionElement>;
            "contact-section": LocalJSX.ContactSection & JSXBase.HTMLAttributes<HTMLContactSectionElement>;
            "footer-section": LocalJSX.FooterSection & JSXBase.HTMLAttributes<HTMLFooterSectionElement>;
            "header-section": LocalJSX.HeaderSection & JSXBase.HTMLAttributes<HTMLHeaderSectionElement>;
            "hero-section": LocalJSX.HeroSection & JSXBase.HTMLAttributes<HTMLHeroSectionElement>;
            "home-page": LocalJSX.HomePage & JSXBase.HTMLAttributes<HTMLHomePageElement>;
            "join-us-section": LocalJSX.JoinUsSection & JSXBase.HTMLAttributes<HTMLJoinUsSectionElement>;
            "login-section": LocalJSX.LoginSection & JSXBase.HTMLAttributes<HTMLLoginSectionElement>;
            "my-router": LocalJSX.MyRouter & JSXBase.HTMLAttributes<HTMLMyRouterElement>;
            "sign-in-section": LocalJSX.SignInSection & JSXBase.HTMLAttributes<HTMLSignInSectionElement>;
            "sports-section": LocalJSX.SportsSection & JSXBase.HTMLAttributes<HTMLSportsSectionElement>;
            "subscription-section": LocalJSX.SubscriptionSection & JSXBase.HTMLAttributes<HTMLSubscriptionSectionElement>;
        }
    }
}
